Master
Gentilitysp/My-Logo pull request #1
Opened 2021-08-12 15:34 UTC by Gentilitysp

Hello Reviewer

This pull request is for you to be able to review my project.

I was able to achieve the following in the project:

- Inserting a background image
- Using Flex to display my work
- Creating a Navigation bar
- Using CSS to set my background image etc

Kindly grant my project a favorable review.

Thanks

2021-08-12 18:02 UTC, karvel-code requested changes
Hi @Gentilitysp , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Proper use of git-flow.
- Your README looks very professional
- All linter checks pass successfully.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please ensure that your image is not wrapped inside the `<img>` tag. It should instead be a background image and not a normal image.
- [ ] Please use the margins provided in the Figma design for the background image. For instance, in the design, there is a very small margin between the image and the end of the edge.
- [ ] Please ensure to enclose/group the social media icons inside the `<ul>` tag instead of the `<section>` tag. Also, ensure that each `<a>` tag is enclosed inside the `<li>` tag.
- [ ] Ensure you align content in the main section using the flexbox.
- [ ] Ensure you follow the design provided by Figma especially the font family of the different sections.

- **Please check the below comments for further instructions on the changes required.**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-12 18:02 UTC, karvel-code commented on index.html
> +  </main>
- [ ] Please ensure that you wrap this entire highlighted section inside a `<section>` tag. This is so as to enhance the semantics of your HTML code.
- [ ] Also, you are required to align content in this section using the flexbox.

2021-08-12 18:02 UTC, karvel-code commented on index.html
> +      </aside>
- [ ] Please ensure that your image is not wrapped inside the `<img>` tag. It should instead be a background image and not a normal image.
- [ ] Please use the margins provided in the figma design for the background image. For instance, in the design, there is a very small margin between the image and the end of the edge.

2021-08-12 18:02 UTC, karvel-code commented on index.html
> +    <h3 class="Welcome">Hey There. <br> I’m Alex</h3>
- [ ] Please change the `<h3>` tag to a `<h1>` tag. This will somehow enhance the visibility of the section which is the main title of your web page.

2021-08-12 18:02 UTC, karvel-code commented on index.html
> +    </section>
- [ ] Please ensure to enclose/group the social media icons inside the `<ul>` tag instead of the `<section>` tag. Also, ensure that each `<a>` tag is enclosed inside the `<li>` tag.

2021-08-12 18:02 UTC, karvel-code commented on styles.css
> +  font-family: 'Crete Round', serif;
- [ ] The font family specified for this section should be _Roboto_ and not _Crete Round_. Please change that.

2021-08-12 18:02 UTC, karvel-code commented on styles.css
> +  font-family: 'Crete Round', serif;
- [ ] Use _Poppins_ as the font family as described in the design instead of _Crete Round_.

2021-08-12 20:56 UTC, addod19 requested changes
### Hi @Gentilitysp , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

__Happy coding__ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2021-08-12 20:56 UTC, addod19 commented on index.html
> +  <main class="main">
- [ ] It would be better if we change `<main class="main">` to `<section class="main">` as pointer out by the previous code reviewer earlier

2021-08-12 20:56 UTC, addod19 commented on index.html
> +    <h3 class="Welcome">Hey There. <br> I’m Alex</h3>
- [ ] It would be better if we address the comment about change the `<h3>` to `<h1>` which is supposed to be the main title or header

2021-08-12 20:56 UTC, addod19 commented on styles.css
> +.page-top {
- [ ] It would be better if we address the spacing/margin of the logo and the hamburger, let us center it and add a little bit of font-weight to it

2021-08-13 00:26 UTC, carlos-ssh approved these changes
Hi @Gentilitysp , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-13 13:45 UTC, merged